extension_paths = {
    'aif':    'media/audio',
    'cda':    'media/audio',
    'mid':    'media/audio',
    'midi':   'media/audio',
    'mp3':    'media/audio',
    'mpa':    'media/audio',
    'ogg':    'media/audio',
    'wav':    'media/audio',
    'wma':    'media/audio',
    'wpl':    'media/audio',
    'm3u':    'media/audio',

    '3g2':    'media/video',
    '3gp':    'media/video',
    'avi':    'media/video',
    'flv':    'media/video',
    'h264':   'media/video',
    'm4v':    'media/video',
    'mkv':    'media/video',
    'mov':    'media/video',
    'mp4':    'media/video',
    'mpg':    'media/video',
    'mpeg':   'media/video',
    'rm':     'media/video',
    'swf':    'media/video',
    'vob':    'media/video',
    'wmv':    'media/video',

    'ai':     'media/images',
    'bmp':    'media/images',
    'gif':    'media/images',
    'jpg':    'media/images',
    'jpeg':   'media/images',
    'png':    'media/images',
    'ps':     'media/images',
    'psd':    'media/images',
    'svg':    'media/images',
    'tif':    'media/images',
    'tiff':   'media/images',
    'cr2':    'media/images',

    'txt':    'text/text_files',
    'doc':    'text/doc_files',
    'docx':   'text/doc_files',
    'odt ':   'text/text_files',
    'pdf':    'text/pdf',
    'rtf':    'text/text_files',
    'tex':    'text/text_files',
    'wks ':   'text/text_files',
    'wps':    'text/text_files',
    'wpd':    'text/text_files',

    'key':    'text/presentations',
    'odp':    'text/presentations',
    'pps':    'text/presentations',
    'ppt':    'text/presentations',
    'pptx':   'text/presentations',

    'bak':    'text/system',
    'cab':    'text/system',
    'cfg':    'text/system',
    'cpl':    'text/system',
    'cur':    'text/system',
    'dll':    'text/system',
    'dmp':    'text/system',
    'drv':    'text/system',
    'icns':   'text/system',
    'ico':    'text/system',
    'ini':    'text/system',
    'lnk':    'text/system',
    'msi':    'text/system',
    'sys':    'text/system',
    'tmp':    'text/system',

    '7z':     'compressed',
    'arj':    'compressed',
    'deb':    'compressed',
    'pkg':    'compressed',
    'rar':    'compressed',
    'rpm':    'compressed',
    'gz':     'compressed',
    'z':      'compressed',
    'zip':    'compressed',

    'asp':    'internet',
    'aspx':   'internet',
    'cer':    'internet',
    'cfm':    'internet',
    'cgi':    'internet',
    'pl':     'internet',
    'css':    'internet',
    'htm':    'internet',
    'js':     'internet',
    'jsp':    'internet',
    'part':   'internet',
    'php':    'internet',
    'rss':    'internet',
    'xhtml':  'internet',
    'html':   'internet',

    'apk':    'executables',
    'bat':    'executables',
    'com':    'executables',
    'exe':    'executables',
    'gadget': 'executables',
    'jar':    'executables',
    'wsf':    'executables',

    'bin':    'disc',
    'dmg':    'disc',
    'iso':    'disc',
    'toast':  'disc',
    'vcd':    'disc',

    'fnt':    'fonts',
    'fon':    'fonts',
    'otf':    'fonts',
    'ttf':    'fonts',

    'csv':    'data',
    'dat':    'data',
    'db':     'data',
    'dbf':    'data',
    'log':    'data',
    'mdb':    'data',
    'sav':    'data',
    'sql':    'data',
    'tar':    'data',
    'xml':    'data',
    'json':   'data',

    'ods':    'data',
    'xlr':    'data',
    'xls':    'data',
    'xlsx':   'data',

    'c':      'programming/c&c++',
    'cpp':    'programming/c&c++',
    'class':  'programming/java',
    'java':   'programming/java',
    'py':     'programming/python',
    'sh':     'programming/shell',
    'h':      'programming/c&c++'
}